### ISSUE TITLE
Feature: User can view NASA's image of the day as well as an inspirational quote

### ISSUE THREAD

**Issue by louiewhitz** [louiewhitz/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view the Nasa image of the day, along with an inspirational quote. User can refresh the page, and view a new inspirational quote.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Create a responsive web page that allows users to view NASA's images on a desktop and mobile device.
There will also be a title, description an date of then the image was taken.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-09-26 at 12 01 06 AM](https://user-images.githubusercontent.com/99847558/192213279-f3f3760b-dfd5-42e2-a970-8dbb9a3fb48d.png)
![Screen Shot 2022-09-26 at 10 28 53 AM](https://user-images.githubusercontent.com/99847558/192342158-e2e7c9fd-7406-4307-92d7-a61b378e3eb7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] Add a div[data-view="start-page"] to the HTML
- [x] Add a fixed nav bar for the main home view, search view, and favorites view
- [x] Add buttons to each in the nav-bar
- [x] Ensure that the image and content look good on both desktop and mobile devices
- [x] Make sure all images fit on both mobile and desktop devices
- [x] Make sure that on page refresh a new quote appears
- [x] Make sure that the date and description of the star match the star of the current date
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by louiewhitz** [comment]
![Screen Shot 2022-09-26 at 11 32 59 AM](https://user-images.githubusercontent.com/99847558/192354499-09fc740d-3761-4529-8850-bcea9d3b1405.png)
![Screen Shot 2022-09-26 at 11 33 35 AM](https://user-images.githubusercontent.com/99847558/192354654-893b52d3-66c8-4936-a0c0-02fdb414d059.png)
