### ISSUE TITLE
FEATURE: User can like image of the day and save to favorites page

### ISSUE THREAD

**Issue by louiewhitz** [louiewhitz/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can like an image, and save it to their favorites page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to like a NASA image and click the favorites tab to view their favorites.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-09-26 at 10 28 53 AM](https://user-images.githubusercontent.com/99847558/192343304-1b2fed08-08d2-48ad-ad80-f13c4c6ce632.png)

![Screen Shot 2022-09-26 at 12 12 05 AM](https://user-images.githubusercontent.com/99847558/192215076-b8d948d2-d395-4e81-a105-f6036b4741ab.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Add the heart icon
- [ ] Add a 'click' event listener on the heart icon
- [ ] Update local storage if the heart icon was clicked by adding a favorites array to the data
- [ ] Give the liked item a data-id in order to keep track of it
- [ ] If there are liked images, create a render function that adds more items to the favorites page, with the most recently liked showing at the top
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
