### ISSUE TITLE
Feature: User can search for NASA image by date

### ISSUE THREAD

**Issue by louiewhitz** [louiewhitz/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can input a date and search for the NASA image of that day, with the option of adding it to their favorites page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 10 14 23 AM](https://user-images.githubusercontent.com/99847558/192339521-b83aa3df-0dca-4b30-b3d8-bc8a03f27f9a.png)
![Screen Shot 2022-09-26 at 10 13 47 AM](https://user-images.githubusercontent.com/99847558/192339523-b3188474-0816-4a87-8ebf-be12b8866b02.png)
![Screen Shot 2022-09-26 at 10 26 19 AM](https://user-images.githubusercontent.com/99847558/192341698-3720f6e8-58ef-4688-b01c-80af20135f0e.png)
![Screen Shot 2022-09-26 at 10 25 46 AM](https://user-images.githubusercontent.com/99847558/192341703-6475da6b-760e-4c62-82f5-8e594e61db43.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] Create modal for search page as a form and give it a data-view 'search-view'
- [x] Add the submit icon
- [x] Add a results page that that has the same HTML and CSS but is populated by the input value
- [x] Add three input events for day month and year
- [x] Add a 'submit' event listener to the icon
- [x] When submitted, create an output function that shows the 'src', title and description of that specific day
- [x] Add a heart icon for so the user may like the image and add it to their favorites page
- [x] Update local storage if person wishes to save the image
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
