### ISSUE TITLE
Feature: User can like an image favorites

### ISSUE THREAD

**Issue by louiewhitz** [louiewhitz/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 10 08 48 AM](https://user-images.githubusercontent.com/99847558/192343641-6ad34db3-d8ac-44b5-9e14-cd164dac8856.png)
![Screen Shot 2022-09-26 at 10 08 17 AM](https://user-images.githubusercontent.com/99847558/192343645-a8e07105-cbd0-4036-a1ac-5be1d276ed8a.png)
![Screen Shot 2022-09-26 at 10 40 14 AM](https://user-images.githubusercontent.com/99847558/192344229-8201cd18-b200-435b-8015-63d8adca2676.png)
![Screen Shot 2022-09-26 at 10 39 56 AM](https://user-images.githubusercontent.com/99847558/192344232-2f07e910-47eb-415c-bc44-b4d786b2fafd.png)
![Screen Shot 2022-09-26 at 10 39 42 AM](https://user-images.githubusercontent.com/99847558/192344235-2f456fad-6e1e-418e-89c8-4125f2176289.png)
![Screen Shot 2022-09-26 at 10 39 13 AM](https://user-images.githubusercontent.com/99847558/192344236-241a8e0b-805d-41f6-8b63-2b5f853e7e32.png)
![Screen Shot 2022-09-26 at 10 39 00 AM](https://user-images.githubusercontent.com/99847558/192344238-c7fef03a-ddab-4ed4-a042-68c027350bc9.png)
![Screen Shot 2022-09-26 at 10 38 39 AM](https://user-images.githubusercontent.com/99847558/192344239-03487768-87e2-4fe5-aeb1-2fb62d47a66d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Create a modal that allows users to know that they haven't saved anything to their favorites page
- [ ] Create a function that checks whether there is any data in local storage
- [ ] Show 'no favorites page' if the user clicks the favorites button and there is no data in the local storage
- [ ] Show favorites page with the most recently liked images at the top
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
