### ISSUE TITLE
Feature: User can unlike an image

### ISSUE THREAD

**Issue by louiewhitz** [louiewhitz/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can unlike any image from their favorites page, and it will automatically disappear

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to unlike a photo and the data will disappear instantaneously

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 10 08 48 AM](https://user-images.githubusercontent.com/99847558/192345210-5cb36cf8-1ed1-498e-9b69-94cc28a5fc93.png)
![Screen Shot 2022-09-26 at 10 08 17 AM](https://user-images.githubusercontent.com/99847558/192345212-3d7ce8e6-abbf-4564-a76e-ba22c651d2f0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Add an event listener to the heart icon that listens to a 'dblick'
- [ ] Create a delete function that deletes the image from local storage according to its ID if the user double clicks the heart icon
- [ ] Make the image disappear immediately as well as the heart icon
- [ ] Make sure on page refresh the image does not show
- [ ] Make sure that when switching tabs the image does not show
- [ ] If all images have been deleted, show the no favorites modal
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
